# Include this file once from the host Nginx `http` context.
limit_req_zone $binary_remote_addr zone=ziyoufang_api_per_ip:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=ziyoufang_auth_per_ip:10m rate=10r/m;
