events {}

http {
  include /etc/nginx/mime.types;
  include /etc/nginx/snippets/host-nginx-api-limits.conf;

  server {
    listen 8080;
    server_name lilicoconut.me;

    location / {
      return 200 'existing website placeholder';
    }

    include /etc/nginx/snippets/host-nginx-api-locations.conf;
  }
}
